name: CI
on:
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-vue3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install dependencies
        working-directory: ./server
        run: 
          npm install
          
      - name: Build Vue3
        working-directory: ./server
        run: 
          npm run build
